### ISSUE TITLE
Crash whilst sprint swimming

### ISSUE THREAD

**Issue by JSJBDEV** [JSJBDEV/Aquarius#2]
https://github.com/architectury/architectury-api/issues/66#issuecomment-813093492

your move @adoxentor xD

**Comment by JSJBDEV** [comment]
I believe ive fixed it using advice from the architectury people, but if you want to check with your knowledge why thats a problem have a look then rebuild it

**Comment by adoxentor** [comment]
My bad...
your fix solves the crash but has wrong behavior.
I fixed it, building and uploading as beta now.
https://github.com/JSJBDEV/Aquarius/blob/54f712faed384dcde035155fd682b388c8b51eb0/fabric/src/main/java/space/bbkr/aquarius/fabric/mixin/MixinPlayerEntity.java#L108-L116
